export const MainMenuList1 = [
  { id: 1, name: "pos", label: "POS", subMenu: [] },
  {
    id: 2,
    name: "inventory",
    label: "Inventory",
    subMenu: [
      { id: 1, name: "stock", label: "Stock" },
      { id: 2, name: "deliveries", label: "Deliveries" },
      { id: 3, name: "warehouse", label: "Warehouse" },
    ],
  },
  {
    id: 3,
    name: "account",
    label: "Account",
    subMenu: [
      { id: 1, name: "profit_loss", label: "P&L" },
      { id: 2, name: "depreciation", label: "Depreciation" },
      { id: 3, name: "account_receivables", label: "Account Receivables" },
      { id: 4, name: "account_payables", label: "Account Payables" },
    ],
  },
  {
    id: 4,
    name: "report",
    label: "Report",
    subMenu: [
      { id: 1, name: "sales_report", label: "Sales Report" },
      { id: 2, name: "stock_report", label: "Stock Report" },
      { id: 3, name: "promo_discount", label: "Promotions & Discounts" },
      { id: 4, name: "refunds", label: "Refunds & Returns" },
    ],
  },
  {
    id: 5,
    name: "businesses",
    label: "Branches",
    subMenu: [
      { id: 1, name: "asaba", label: "Grill & Crust Asaba" },
      { id: 2, name: "lagos", label: "Grill & Crust Lagos" },
    ],
  },
  {
    id: 6,
    name: "settings",
    label: "Settings",
    subMenu: [
      { id: 1, name: "users_roles", label: "Users & Roles" },
      { id: 2, name: "payment_method", label: "Payment Methods" },
    ],
  },
  {
    id: 7,
    name: "promo_discount",
    label: "Promotions & Discounts",
    subMenu: [
      { id: 1, name: "promotions", label: "Promotions" },
      { id: 2, name: "discounts", label: "Discounts" },
      { id: 3, name: "tax", label: "Tax Settings" },
    ],
  },
  {
    id: 8,
    name: "customers",
    label: "Customers",
    subMenu: [
      { id: 1, name: "customer-list", label: "Customer List" },
      { id: 2, name: "loyalty", label: "Loyalty Program" },
      { id: 3, name: "feedback", label: "Customer Feedback" },
      { id: 4, name: "campaigns", label: "Email/SMS Campaigns" },
    ],
  },
  {
    id: 9,
    name: "sales",
    label: "Sales & Orders",
    subMenu: [
      { id: 1, name: "invoices", label: "Invoices" },
      { id: 2, name: "quotations", label: "Quotations" },
      { id: 3, name: "returns", label: "Returns" },
      { id: 4, name: "delivery_notes", label: "Delivery Notes" },
    ],
  },
  {
    id: 10,
    name: "purchases",
    label: "Suppliers & Procurement",
    subMenu: [
      { id: 1, name: "purchase_orders", label: "Purchase Orders" },
      { id: 2, name: "suppliers", label: "Suppliers" },
      { id: 3, name: "supplier_payments", label: "Supplier Payments" },
    ],
  },
  {
    id: 11,
    name: "audit",
    label: "Audit Trail",
    subMenu: [
      { id: 1, name: "user_logs", label: "User Activity Logs" },
      { id: 2, name: "system_logs", label: "System Logs" },
    ],
  },
  {
    id: 12,
    name: "cash_management",
    label: "Cash & Banks",
    subMenu: [
      { id: 1, name: "cash_drawer", label: "Cash Drawer" },
      { id: 2, name: "bank_accounts", label: "Bank Accounts" },
      { id: 3, name: "reconciliation", label: "Bank Reconciliation" },
    ],
  },
  {
    id: 13,
    name: "assets",
    label: "Fixed Assets",
    subMenu: [
      { id: 1, name: "asset-list", label: "Asset List" },
      { id: 2, name: "maintenance", label: "Maintenance Logs" },
    ],
  },
];

export const MainMenuList2 = [
  {
    id: 1,
    name: "pos",
    label: "Point of Sale",
    icon: "terminal",
    subMenu: [
      { id: 1, name: "quick_sale", label: "Quick Sale", shortcut: "F1" },
      {
        id: 2,
        name: "order_history",
        label: "Order History",
        features: [
          {
            name: "search",
            type: "standard",
            description: "Full-text search across order attributes",
            requiredPermissions: ["orders.read"],
          },
          {
            name: "filter",
            type: "advanced",
            description: "Multi-criteria filtering with saved presets",
            requiredPermissions: ["orders.advanced_view"],
            premium: true,
          },
        ],
      },
      {
        id: 3,
        name: "hold_orders",
        label: "Hold Orders",
        features: ["timeout"],
      },
      {
        id: 4,
        name: "split_bill",
        label: "Bill Splitting",
        features: ["percentage", "equal"],
      },
      {
        id: 5,
        name: "kitchen_display",
        label: "Kitchen Display",
        features: ["priority"],
      },
      {
        id: 6,
        name: "table_management",
        label: "Table Management",
        features: ["floor_plan"],
      },
      {
        id: 7,
        name: "credit_sales",
        label: "Credit Sales",
        features: ["credit_limit"],
      },
      {
        id: 8,
        name: "installments",
        label: "Installment Tracker",
        features: ["reminders"],
      },
      {
        id: 9,
        name: "cash_drawer",
        label: "Cash Drawer Operations",
        features: ["shift_report"],
      },
      {
        id: 10,
        name: "end_of_day",
        label: "End of Day Reconciliation",
        features: ["variance"],
      },
      { id: 11, name: "mobile_pos", label: "Mobile POS", premium: true },
      {
        id: 12,
        name: "self_checkout",
        label: "Self-Checkout Kiosk",
        enterprise: true,
      },
    ],
  },
  {
    id: 2,
    name: "inventory",
    label: "Inventory Control",
    icon: "warehouse",
    subMenu: [
      {
        id: 1,
        name: "stock_management",
        label: "Stock Management",
        features: ["barcode", "batch", "serial"],
      },
      {
        id: 2,
        name: "deliveries",
        label: "Receiving & Deliveries",
        features: ["po_matching"],
      },
      {
        id: 3,
        name: "warehouse",
        label: "Warehouse Management",
        features: ["multi-location", "bin"],
      },
      {
        id: 4,
        name: "inventory_audit",
        label: "Cycle Counting",
        features: ["variance"],
      },
      {
        id: 5,
        name: "supplier_management",
        label: "Supplier Management",
        features: ["performance"],
      },
      {
        id: 6,
        name: "low_stock",
        label: "Low Stock Alerts",
        features: ["thresholds"],
      },
      {
        id: 7,
        name: "product_matrix",
        label: "Product Matrix (Variants)",
        features: ["attributes"],
      },
      {
        id: 8,
        name: "demand_forecasting",
        label: "Demand Forecasting",
        premium: true,
      },
      {
        id: 9,
        name: "auto_replenishment",
        label: "Auto Replenishment",
        enterprise: true,
      },
      {
        id: 10,
        name: "inventory_valuation",
        label: "Inventory Valuation",
        features: ["FIFO", "LIFO"],
      },
    ],
  },
  {
    id: 3,
    name: "financial",
    label: "Financial Suite",
    icon: "chart-line",
    subMenu: [
      {
        id: 1,
        name: "profit_loss",
        label: "P&L Dashboard",
        features: ["comparative"],
      },
      {
        id: 2,
        name: "depreciation",
        label: "Asset Depreciation",
        features: ["methods"],
      },
      {
        id: 3,
        name: "receivables",
        label: "AR Management",
        features: ["aging", "dunning"],
      },
      {
        id: 4,
        name: "payables",
        label: "AP Management",
        features: ["aging", "approvals"],
      },
      {
        id: 5,
        name: "cash_flow",
        label: "Cash Flow Analysis",
        features: ["projections"],
      },
      {
        id: 6,
        name: "budgeting",
        label: "Budget Planning",
        features: ["scenarios"],
      },
      {
        id: 7,
        name: "tax_center",
        label: "Tax Center",
        features: ["jurisdictions"],
      },
      {
        id: 8,
        name: "financial_consolidation",
        label: "Financial Consolidation",
        enterprise: true,
      },
      {
        id: 9,
        name: "currency_management",
        label: "Multi-Currency",
        features: ["fx_rates"],
      },
    ],
  },
  {
    id: 4,
    name: "analytics",
    label: "Business Intelligence",
    icon: "database",
    subMenu: [
      {
        id: 1,
        name: "sales_analytics",
        label: "Sales Analytics",
        features: ["kpi", "trends"],
      },
      {
        id: 2,
        name: "inventory_analytics",
        label: "Inventory Analytics",
        features: ["turnover"],
      },
      {
        id: 3,
        name: "customer_analytics",
        label: "Customer Insights",
        features: ["segmentation"],
      },
      {
        id: 4,
        name: "employee_analytics",
        label: "Labor Analytics",
        features: ["productivity"],
      },
      {
        id: 5,
        name: "predictive",
        label: "Predictive Analytics",
        premium: true,
      },
      {
        id: 6,
        name: "custom_reports",
        label: "Custom Report Builder",
        features: ["drag-drop"],
      },
      {
        id: 7,
        name: "data_warehouse",
        label: "Data Warehouse",
        enterprise: true,
      },
      {
        id: 8,
        name: "real-time_dashboards",
        label: "Real-Time Dashboards",
        features: ["alerts"],
      },
    ],
  },
  {
    id: 5,
    name: "multi_location",
    label: "Multi-Location",
    icon: "store-alt",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "location_dashboard",
        label: "Location Dashboard",
        features: ["comparison"],
      },
      {
        id: 2,
        name: "interbranch",
        label: "Interbranch Transfers",
        features: ["tracking"],
      },
      {
        id: 3,
        name: "consolidated",
        label: "Consolidated Reporting",
        features: ["drill-down"],
      },
      {
        id: 4,
        name: "franchise",
        label: "Franchise Management",
        features: ["royalties"],
      },
      {
        id: 5,
        name: "geo_analytics",
        label: "Geographic Analytics",
        features: ["heatmaps"],
      },
      {
        id: 6,
        name: "central_kitchen",
        label: "Central Kitchen Management",
        premium: true,
      },
    ],
  },
  {
    id: 6,
    name: "customer",
    label: "Customer Hub",
    icon: "users",
    subMenu: [
      { id: 1, name: "crm", label: "CRM Dashboard", features: ["360-view"] },
      {
        id: 2,
        name: "loyalty",
        label: "Loyalty Programs",
        features: ["tiers", "burn"],
      },
      {
        id: 3,
        name: "feedback",
        label: "Feedback System",
        features: ["sentiment"],
      },
      {
        id: 4,
        name: "marketing",
        label: "Marketing Automation",
        features: ["campaigns"],
      },
      {
        id: 5,
        name: "gift_cards",
        label: "Gift Card Management",
        features: ["issuance"],
      },
      {
        id: 6,
        name: "memberships",
        label: "Membership Programs",
        features: ["renewals"],
      },
      {
        id: 7,
        name: "customer_portal",
        label: "Customer Self-Service",
        premium: true,
      },
      {
        id: 8,
        name: "voice_of_customer",
        label: "Voice of Customer",
        enterprise: true,
      },
    ],
  },
  {
    id: 7,
    name: "hr",
    label: "HR & Payroll",
    icon: "user-tie",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "employee",
        label: "Employee Management",
        features: ["onboarding"],
      },
      {
        id: 2,
        name: "scheduling",
        label: "Scheduling & Time Tracking",
        features: ["auto-scheduling"],
      },
      {
        id: 3,
        name: "payroll",
        label: "Payroll Processing",
        features: ["tax-filing"],
      },
      {
        id: 4,
        name: "performance",
        label: "Performance Tracking",
        features: ["kpi"],
      },
      {
        id: 5,
        name: "training",
        label: "Training Modules",
        features: ["certifications"],
      },
      {
        id: 6,
        name: "labor_analytics",
        label: "Labor Cost Optimization",
        premium: true,
      },
    ],
  },
  {
    id: 8,
    name: "ecommerce",
    label: "E-Commerce",
    icon: "shopping-cart",
    subMenu: [
      {
        id: 1,
        name: "online_orders",
        label: "Online Order Management",
        features: ["aggregation"],
      },
      {
        id: 2,
        name: "menu_sync",
        label: "Menu Synchronization",
        features: ["real-time"],
      },
      {
        id: 3,
        name: "delivery",
        label: "Delivery Integration",
        features: ["dispatch"],
      },
      {
        id: 4,
        name: "marketplace",
        label: "Marketplace Connectors",
        features: ["multi-channel"],
      },
      { id: 5, name: "click_collect", label: "Click & Collect", premium: true },
      {
        id: 6,
        name: "dark_kitchen",
        label: "Dark Kitchen Mode",
        enterprise: true,
      },
      {
        id: 7,
        name: "qr_shopping",
        label: "Mobile QR Shopping",
        features: ["inventory_lookup", "cart_sync", "pos_payment_link"],
        integration: {
          pos: true,
          inventory: true,
          payment: true,
        },
      },
    ],
  },
  {
    id: 9,
    name: "system",
    label: "System Administration",
    icon: "cogs",
    adminOnly: true,
    subMenu: [
      {
        id: 1,
        name: "users",
        label: "User & Role Management",
        features: ["mfa"],
      },
      {
        id: 2,
        name: "permissions",
        label: "Permission Matrix",
        features: ["granular"],
      },
      {
        id: 3,
        name: "integrations",
        label: "API & Integrations",
        features: ["webhooks"],
      },
      { id: 4, name: "backup", label: "Backup & Restore", features: ["cloud"] },
      {
        id: 5,
        name: "hardware",
        label: "Hardware Configuration",
        features: ["profiles"],
      },
      {
        id: 6,
        name: "license",
        label: "License Management",
        features: ["usage"],
      },
      {
        id: 7,
        name: "support",
        label: "Issue Tracker / Support Requests",
        features: ["sla"],
      },
      {
        id: 8,
        name: "release_notes",
        label: "Release Notes & Updates",
        features: ["changelog"],
      },
    ],
  },
  {
    id: 10,
    name: "audit",
    label: "Audit & Compliance",
    icon: "shield-alt",
    subMenu: [
      {
        id: 1,
        name: "activity_logs",
        label: "Activity Audit Trail",
        features: ["reconstruction"],
      },
      {
        id: 2,
        name: "financial_audit",
        label: "Financial Auditing",
        features: ["snapshots"],
      },
      {
        id: 3,
        name: "pci_compliance",
        label: "PCI Compliance",
        features: ["scans"],
      },
      {
        id: 4,
        name: "data_export",
        label: "Regulatory Exports",
        features: ["templates"],
      },
      {
        id: 5,
        name: "sarbanes_oxley",
        label: "SOX Controls",
        enterprise: true,
      },
    ],
  },
  {
    id: 11,
    name: "advanced",
    label: "Advanced Features",
    icon: "magic",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "ai",
        label: "AI Recommendations",
        premium: true,
        features: ["upsell"],
      },
      {
        id: 2,
        name: "recipe",
        label: "Recipe & Menu Engineering",
        features: ["costing"],
      },
      {
        id: 3,
        name: "waste",
        label: "Waste Tracking",
        features: ["root-cause"],
      },
      {
        id: 4,
        name: "kds",
        label: "Kitchen Display System",
        features: ["ai-routing"],
      },
      {
        id: 5,
        name: "reservations",
        label: "Reservation System",
        features: ["yield"],
      },
      {
        id: 6,
        name: "product_lifecycle",
        label: "Product Lifecycle Mgmt",
        features: ["phase"],
      },
      { id: 7, name: "iot", label: "IoT Device Integration", premium: true },
      {
        id: 8,
        name: "blockchain",
        label: "Blockchain Traceability",
        enterprise: true,
      },
    ],
  },
];

export const MainMenuList = [
  {
    id: 1,
    name: "pos",
    label: "Point of Sale",
    icon: "terminal",
    subMenu: [
      {
        id: 1,
        name: "quick_sale",
        label: "Quick Sale",
        shortcut: "F1",
        features: [
          {
            name: "express_checkout",
            type: "core",
            description: "Single-screen transaction processing",
            requiredPermissions: ["pos.create"],
          },
        ],
      },
      {
        id: 2,
        name: "order_history",
        label: "Order History",
        features: [
          {
            name: "search",
            type: "standard",
            description: "Full-text search across order attributes",
            requiredPermissions: ["orders.read"],
          },
          {
            name: "filter",
            type: "advanced",
            description: "Multi-criteria filtering with saved presets",
            requiredPermissions: ["orders.advanced_view"],
            premium: true,
          },
          {
            name: "export",
            type: "standard",
            description: "Export to CSV/PDF formats",
            requiredPermissions: ["orders.export"],
          },
        ],
      },
      {
        id: 3,
        name: "hold_orders",
        label: "Hold Orders",
        features: [
          {
            name: "timeout",
            type: "standard",
            description: "Automatic order expiration after set time",
            requiredPermissions: ["orders.hold"],
          },
          {
            name: "recovery",
            type: "standard",
            description: "Recover held orders with original state",
            requiredPermissions: ["orders.hold"],
          },
        ],
      },
      {
        id: 4,
        name: "split_bill",
        label: "Bill Splitting",
        features: [
          {
            name: "percentage",
            type: "standard",
            description: "Split by percentage allocation",
            requiredPermissions: ["orders.modify"],
          },
          {
            name: "equal",
            type: "standard",
            description: "Equal division of total amount",
            requiredPermissions: ["orders.modify"],
          },
          {
            name: "custom",
            type: "advanced",
            description: "Manual amount allocation",
            requiredPermissions: ["orders.advanced"],
            premium: true,
          },
        ],
      },
      {
        id: 5,
        name: "kitchen_display",
        label: "Kitchen Display",
        features: [
          {
            name: "priority",
            type: "standard",
            description: "Priority order tagging",
            requiredPermissions: ["kitchen.view"],
          },
          {
            name: "modifiers",
            type: "standard",
            description: "Special instructions display",
            requiredPermissions: ["kitchen.view"],
          },
          {
            name: "status",
            type: "standard",
            description: "Real-time order status updates",
            requiredPermissions: ["kitchen.view"],
          },
        ],
      },
      {
        id: 6,
        name: "table_management",
        label: "Table Management",
        features: [
          {
            name: "floor_plan",
            type: "standard",
            description: "Visual table layout editor",
            requiredPermissions: ["tables.manage"],
          },
          {
            name: "merge",
            type: "standard",
            description: "Combine multiple tables",
            requiredPermissions: ["tables.manage"],
          },
          {
            name: "transfer",
            type: "standard",
            description: "Move orders between tables",
            requiredPermissions: ["tables.manage"],
          },
        ],
      },
      {
        id: 7,
        name: "credit_sales",
        label: "Credit Sales",
        features: [
          {
            name: "credit_limit",
            type: "standard",
            description: "Customer credit limit enforcement",
            requiredPermissions: ["sales.credit"],
          },
          {
            name: "terms",
            type: "standard",
            description: "Custom payment terms",
            requiredPermissions: ["sales.credit"],
          },
          {
            name: "aging",
            type: "advanced",
            description: "Aging report integration",
            requiredPermissions: ["sales.credit.reports"],
            premium: true,
          },
        ],
      },
      {
        id: 8,
        name: "installments",
        label: "Installment Tracker",
        features: [
          {
            name: "reminders",
            type: "standard",
            description: "Automatic payment reminders",
            requiredPermissions: ["sales.installments"],
          },
          {
            name: "reschedule",
            type: "standard",
            description: "Payment plan adjustments",
            requiredPermissions: ["sales.installments"],
          },
          {
            name: "auto_charge",
            type: "premium",
            description: "Automatic payment processing",
            requiredPermissions: ["sales.installments.auto"],
            premium: true,
          },
        ],
      },
      {
        id: 9,
        name: "cash_drawer",
        label: "Cash Drawer Operations",
        features: [
          {
            name: "shift_report",
            type: "standard",
            description: "End-of-shift reconciliation",
            requiredPermissions: ["cash.manage"],
          },
          {
            name: "float",
            type: "standard",
            description: "Starting float amount tracking",
            requiredPermissions: ["cash.manage"],
          },
          {
            name: "safe_drops",
            type: "standard",
            description: "Record cash removed for deposit",
            requiredPermissions: ["cash.manage"],
          },
        ],
      },
      {
        id: 10,
        name: "end_of_day",
        label: "End of Day Reconciliation",
        features: [
          {
            name: "variance",
            type: "standard",
            description: "Cash variance reporting",
            requiredPermissions: ["reports.daily"],
          },
          {
            name: "z_report",
            type: "standard",
            description: "Final daily sales report",
            requiredPermissions: ["reports.daily"],
          },
          {
            name: "auto_close",
            type: "premium",
            description: "Automated business day closing",
            requiredPermissions: ["reports.daily.auto"],
            premium: true,
          },
        ],
      },
      {
        id: 11,
        name: "mobile_pos",
        label: "Mobile POS",
        premium: true,
        features: [
          {
            name: "offline_mode",
            type: "premium",
            description: "Operation without internet connection",
            requiredPermissions: ["pos.mobile"],
            premium: true,
          },
          {
            name: "tablet_ui",
            type: "premium",
            description: "Optimized tablet interface",
            requiredPermissions: ["pos.mobile"],
            premium: true,
          },
        ],
      },
      {
        id: 12,
        name: "self_checkout",
        label: "Self-Checkout Kiosk",
        enterprise: true,
        features: [
          {
            name: "auto_age_verification",
            type: "enterprise",
            description: "ID scanning for age-restricted items",
            requiredPermissions: ["pos.selfcheckout"],
            enterprise: true,
          },
          {
            name: "weight_verification",
            type: "enterprise",
            description: "Integrated scale validation",
            requiredPermissions: ["pos.selfcheckout"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "inventory",
    label: "Inventory Control",
    icon: "warehouse",
    subMenu: [
      {
        id: 1,
        name: "stock_management",
        label: "Stock Management",
        features: [
          {
            name: "barcode",
            type: "core",
            description: "Barcode generation and scanning",
            requiredPermissions: ["inventory.manage"],
          },
          {
            name: "batch",
            type: "advanced",
            description: "Batch/lot number tracking",
            requiredPermissions: ["inventory.batch"],
            premium: true,
          },
          {
            name: "serial",
            type: "enterprise",
            description: "Serial number tracking",
            requiredPermissions: ["inventory.serial"],
            enterprise: true,
          },
          {
            name: "movement",
            type: "standard",
            description: "Stock movement history",
            requiredPermissions: ["inventory.view"],
          },
        ],
      },
      {
        id: 2,
        name: "deliveries",
        label: "Receiving & Deliveries",
        features: [
          {
            name: "po_matching",
            type: "standard",
            description: "PO to delivery matching system",
            requiredPermissions: ["inventory.receive"],
          },
          {
            name: "qc",
            type: "advanced",
            description: "Quality control checks",
            requiredPermissions: ["inventory.qc"],
          },
          {
            name: "putaway",
            type: "standard",
            description: "Stock putaway process",
            requiredPermissions: ["inventory.receive"],
          },
        ],
      },
      {
        id: 3,
        name: "warehouse",
        label: "Warehouse Management",
        features: [
          {
            name: "multi-location",
            type: "standard",
            description: "Multiple storage locations",
            requiredPermissions: ["inventory.locations"],
          },
          {
            name: "bin",
            type: "advanced",
            description: "Bin/shelf location tracking",
            requiredPermissions: ["inventory.locations.detail"],
            premium: true,
          },
          {
            name: "pick_path",
            type: "enterprise",
            description: "Optimized picking paths",
            requiredPermissions: ["inventory.warehouse.optimize"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "inventory_audit",
        label: "Cycle Counting",
        features: [
          {
            name: "variance",
            type: "standard",
            description: "Count variance reporting",
            requiredPermissions: ["inventory.audit"],
          },
          {
            name: "partial",
            type: "standard",
            description: "Partial location counting",
            requiredPermissions: ["inventory.audit"],
          },
          {
            name: "blind",
            type: "advanced",
            description: "Blind count mode",
            requiredPermissions: ["inventory.audit.advanced"],
            premium: true,
          },
        ],
      },
      {
        id: 5,
        name: "supplier_management",
        label: "Supplier Management",
        features: [
          {
            name: "performance",
            type: "standard",
            description: "Supplier performance metrics",
            requiredPermissions: ["suppliers.view"],
          },
          {
            name: "lead_time",
            type: "standard",
            description: "Delivery time tracking",
            requiredPermissions: ["suppliers.view"],
          },
          {
            name: "contracts",
            type: "advanced",
            description: "Contract terms storage",
            requiredPermissions: ["suppliers.manage"],
            premium: true,
          },
        ],
      },
      {
        id: 6,
        name: "low_stock",
        label: "Low Stock Alerts",
        features: [
          {
            name: "thresholds",
            type: "standard",
            description: "Customizable alert levels",
            requiredPermissions: ["inventory.alerts"],
          },
          {
            name: "notifications",
            type: "standard",
            description: "Multi-channel alerts",
            requiredPermissions: ["inventory.alerts"],
          },
          {
            name: "auto_po",
            type: "enterprise",
            description: "Automatic PO generation",
            requiredPermissions: ["inventory.alerts.auto"],
            enterprise: true,
          },
        ],
      },
      {
        id: 7,
        name: "product_matrix",
        label: "Product Matrix (Variants)",
        features: [
          {
            name: "attributes",
            type: "standard",
            description: "Variant attribute management",
            requiredPermissions: ["products.manage"],
          },
          {
            name: "pricing",
            type: "standard",
            description: "Variant-specific pricing",
            requiredPermissions: ["products.pricing"],
          },
          {
            name: "inventory",
            type: "standard",
            description: "Per-variant stock tracking",
            requiredPermissions: ["products.inventory"],
          },
        ],
      },
      {
        id: 8,
        name: "demand_forecasting",
        label: "Demand Forecasting",
        premium: true,
        features: [
          {
            name: "history",
            type: "premium",
            description: "Historical sales analysis",
            requiredPermissions: ["reports.forecasting"],
            premium: true,
          },
          {
            name: "seasonality",
            type: "premium",
            description: "Seasonal trend adjustments",
            requiredPermissions: ["reports.forecasting"],
            premium: true,
          },
          {
            name: "promo_impact",
            type: "enterprise",
            description: "Promotion impact modeling",
            requiredPermissions: ["reports.forecasting.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 9,
        name: "auto_replenishment",
        label: "Auto Replenishment",
        enterprise: true,
        features: [
          {
            name: "min_max",
            type: "enterprise",
            description: "Minimum/maximum level triggers",
            requiredPermissions: ["inventory.auto"],
            enterprise: true,
          },
          {
            name: "supplier_rules",
            type: "enterprise",
            description: "Supplier-specific ordering rules",
            requiredPermissions: ["inventory.auto"],
            enterprise: true,
          },
        ],
      },
      {
        id: 10,
        name: "inventory_valuation",
        label: "Inventory Valuation",
        features: [
          {
            name: "FIFO",
            type: "standard",
            description: "First-in-first-out costing",
            requiredPermissions: ["reports.valuation"],
          },
          {
            name: "LIFO",
            type: "standard",
            description: "Last-in-first-out costing",
            requiredPermissions: ["reports.valuation"],
          },
          {
            name: "average",
            type: "standard",
            description: "Weighted average costing",
            requiredPermissions: ["reports.valuation"],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "financial",
    label: "Financial Suite",
    icon: "chart-line",
    subMenu: [
      {
        id: 1,
        name: "profit_loss",
        label: "P&L Dashboard",
        features: [
          {
            name: "comparative",
            type: "standard",
            description: "Period-over-period comparisons",
            requiredPermissions: ["financial.report"],
          },
          {
            name: "drilldown",
            type: "advanced",
            description: "Transaction-level drilldown",
            requiredPermissions: ["financial.detail"],
            premium: true,
          },
          {
            name: "departmental",
            type: "enterprise",
            description: "Department-level breakdown",
            requiredPermissions: ["financial.department"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "depreciation",
        label: "Asset Depreciation",
        features: [
          {
            name: "methods",
            type: "standard",
            description: "Multiple depreciation methods",
            requiredPermissions: ["assets.depreciation"],
          },
          {
            name: "schedules",
            type: "standard",
            description: "Custom depreciation schedules",
            requiredPermissions: ["assets.depreciation"],
          },
          {
            name: "projections",
            type: "advanced",
            description: "Future value projections",
            requiredPermissions: ["assets.depreciation.advanced"],
            premium: true,
          },
        ],
      },
      {
        id: 3,
        name: "receivables",
        label: "AR Management",
        features: [
          {
            name: "aging",
            type: "standard",
            description: "Aging receivables reports",
            requiredPermissions: ["receivables.view"],
          },
          {
            name: "dunning",
            type: "advanced",
            description: "Automated collection process",
            requiredPermissions: ["receivables.manage"],
            premium: true,
          },
          {
            name: "write_off",
            type: "standard",
            description: "Bad debt write-off processing",
            requiredPermissions: ["receivables.manage"],
          },
        ],
      },
      {
        id: 4,
        name: "payables",
        label: "AP Management",
        features: [
          {
            name: "aging",
            type: "standard",
            description: "Aging payables reports",
            requiredPermissions: ["payables.view"],
          },
          {
            name: "approvals",
            type: "standard",
            description: "Multi-level invoice approval",
            requiredPermissions: ["payables.approve"],
          },
          {
            name: "payment_runs",
            type: "advanced",
            description: "Batch payment processing",
            requiredPermissions: ["payables.process"],
            premium: true,
          },
        ],
      },
      {
        id: 5,
        name: "cash_flow",
        label: "Cash Flow Analysis",
        features: [
          {
            name: "projections",
            type: "standard",
            description: "Future cash position forecasting",
            requiredPermissions: ["cashflow.view"],
          },
          {
            name: "scenarios",
            type: "advanced",
            description: "What-if scenario modeling",
            requiredPermissions: ["cashflow.advanced"],
            premium: true,
          },
          {
            name: "alerting",
            type: "standard",
            description: "Low cash position alerts",
            requiredPermissions: ["cashflow.view"],
          },
        ],
      },
      {
        id: 6,
        name: "budgeting",
        label: "Budget Planning",
        features: [
          {
            name: "scenarios",
            type: "standard",
            description: "Multiple budget versions",
            requiredPermissions: ["budget.manage"],
          },
          {
            name: "rollover",
            type: "standard",
            description: "Automatic period rollover",
            requiredPermissions: ["budget.manage"],
          },
          {
            name: "variance",
            type: "advanced",
            description: "Actual vs budget analysis",
            requiredPermissions: ["budget.analyze"],
            premium: true,
          },
        ],
      },
      {
        id: 7,
        name: "tax_center",
        label: "Tax Center",
        features: [
          {
            name: "jurisdictions",
            type: "standard",
            description: "Multi-jurisdiction tax rules",
            requiredPermissions: ["tax.manage"],
          },
          {
            name: "filing",
            type: "advanced",
            description: "Tax form generation",
            requiredPermissions: ["tax.file"],
            premium: true,
          },
          {
            name: "nexus",
            type: "enterprise",
            description: "Nexus determination logic",
            requiredPermissions: ["tax.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 8,
        name: "financial_consolidation",
        label: "Financial Consolidation",
        enterprise: true,
        features: [
          {
            name: "currency",
            type: "enterprise",
            description: "Multi-currency consolidation",
            requiredPermissions: ["consolidation.manage"],
            enterprise: true,
          },
          {
            name: "eliminations",
            type: "enterprise",
            description: "Intercompany eliminations",
            requiredPermissions: ["consolidation.manage"],
            enterprise: true,
          },
          {
            name: "ownership",
            type: "enterprise",
            description: "Partial ownership accounting",
            requiredPermissions: ["consolidation.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 9,
        name: "currency_management",
        label: "Multi-Currency",
        features: [
          {
            name: "fx_rates",
            type: "standard",
            description: "Exchange rate management",
            requiredPermissions: ["currency.manage"],
          },
          {
            name: "revaluation",
            type: "advanced",
            description: "Automatic balance revaluation",
            requiredPermissions: ["currency.revalue"],
            premium: true,
          },
          {
            name: "gain_loss",
            type: "standard",
            description: "Realized/unrealized gain/loss tracking",
            requiredPermissions: ["currency.view"],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "analytics",
    label: "Business Intelligence",
    icon: "database",
    subMenu: [
      {
        id: 1,
        name: "sales_analytics",
        label: "Sales Analytics",
        features: [
          {
            name: "kpi",
            type: "standard",
            description: "Key performance indicators dashboard",
            requiredPermissions: ["analytics.sales"],
          },
          {
            name: "trends",
            type: "standard",
            description: "Historical sales trend analysis",
            requiredPermissions: ["analytics.sales"],
          },
          {
            name: "product_mix",
            type: "advanced",
            description: "Product contribution analysis",
            requiredPermissions: ["analytics.sales.advanced"],
            premium: true,
          },
        ],
      },
      {
        id: 2,
        name: "inventory_analytics",
        label: "Inventory Analytics",
        features: [
          {
            name: "turnover",
            type: "standard",
            description: "Inventory turnover ratios",
            requiredPermissions: ["analytics.inventory"],
          },
          {
            name: "obsolescence",
            type: "advanced",
            description: "Slow-moving/obsolete stock identification",
            requiredPermissions: ["analytics.inventory.advanced"],
            premium: true,
          },
          {
            name: "holding_cost",
            type: "enterprise",
            description: "Inventory carrying cost calculation",
            requiredPermissions: ["analytics.inventory.cost"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "customer_analytics",
        label: "Customer Insights",
        features: [
          {
            name: "segmentation",
            type: "standard",
            description: "RFM (Recency, Frequency, Monetary) analysis",
            requiredPermissions: ["analytics.customers"],
          },
          {
            name: "lifetime_value",
            type: "advanced",
            description: "Customer lifetime value modeling",
            requiredPermissions: ["analytics.customers.advanced"],
            premium: true,
          },
          {
            name: "churn",
            type: "enterprise",
            description: "Churn prediction analytics",
            requiredPermissions: ["analytics.customers.churn"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "employee_analytics",
        label: "Labor Analytics",
        features: [
          {
            name: "productivity",
            type: "standard",
            description: "Sales per labor hour metrics",
            requiredPermissions: ["analytics.labor"],
          },
          {
            name: "scheduling",
            type: "advanced",
            description: "Optimal scheduling recommendations",
            requiredPermissions: ["analytics.labor.advanced"],
            premium: true,
          },
          {
            name: "attrition",
            type: "enterprise",
            description: "Employee retention analysis",
            requiredPermissions: ["analytics.labor.attrition"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "predictive",
        label: "Predictive Analytics",
        premium: true,
        features: [
          {
            name: "demand",
            type: "premium",
            description: "AI-driven demand forecasting",
            requiredPermissions: ["analytics.predictive"],
            premium: true,
          },
          {
            name: "pricing",
            type: "premium",
            description: "Dynamic pricing recommendations",
            requiredPermissions: ["analytics.predictive"],
            premium: true,
          },
          {
            name: "maintenance",
            type: "enterprise",
            description: "Equipment failure prediction",
            requiredPermissions: ["analytics.predictive.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "custom_reports",
        label: "Custom Report Builder",
        features: [
          {
            name: "drag-drop",
            type: "standard",
            description: "Visual report designer",
            requiredPermissions: ["reports.create"],
          },
          {
            name: "templates",
            type: "standard",
            description: "Save and share report templates",
            requiredPermissions: ["reports.create"],
          },
          {
            name: "scheduled",
            type: "advanced",
            description: "Automated report distribution",
            requiredPermissions: ["reports.schedule"],
            premium: true,
          },
        ],
      },
      {
        id: 7,
        name: "data_warehouse",
        label: "Data Warehouse",
        enterprise: true,
        features: [
          {
            name: "etl",
            type: "enterprise",
            description: "Extract-Transform-Load pipelines",
            requiredPermissions: ["data.warehouse"],
            enterprise: true,
          },
          {
            name: "cubes",
            type: "enterprise",
            description: "OLAP cube processing",
            requiredPermissions: ["data.warehouse"],
            enterprise: true,
          },
          {
            name: "api",
            type: "enterprise",
            description: "Direct query access via API",
            requiredPermissions: ["data.warehouse.api"],
            enterprise: true,
          },
        ],
      },
      {
        id: 8,
        name: "real-time_dashboards",
        label: "Real-Time Dashboards",
        features: [
          {
            name: "alerts",
            type: "standard",
            description: "Threshold-based notifications",
            requiredPermissions: ["dashboards.view"],
          },
          {
            name: "kiosk",
            type: "advanced",
            description: "Public display mode",
            requiredPermissions: ["dashboards.kiosk"],
            premium: true,
          },
          {
            name: "mobile",
            type: "standard",
            description: "Mobile-optimized views",
            requiredPermissions: ["dashboards.view"],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "multi_location",
    label: "Multi-Location",
    icon: "store-alt",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "location_dashboard",
        label: "Location Dashboard",
        features: [
          {
            name: "comparison",
            type: "standard",
            description: "Cross-location performance benchmarking",
            requiredPermissions: ["locations.compare"],
          },
          {
            name: "scorecard",
            type: "standard",
            description: "Location health scorecard",
            requiredPermissions: ["locations.view"],
          },
          {
            name: "drillthrough",
            type: "advanced",
            description: "Drill into location details",
            requiredPermissions: ["locations.detail"],
            premium: true,
          },
        ],
      },
      {
        id: 2,
        name: "interbranch",
        label: "Interbranch Transfers",
        features: [
          {
            name: "tracking",
            type: "standard",
            description: "Transfer order tracking",
            requiredPermissions: ["transfers.create"],
          },
          {
            name: "costing",
            type: "advanced",
            description: "Transfer pricing calculations",
            requiredPermissions: ["transfers.costing"],
            premium: true,
          },
          {
            name: "auto_routing",
            type: "enterprise",
            description: "Intelligent transfer routing",
            requiredPermissions: ["transfers.auto"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "consolidated",
        label: "Consolidated Reporting",
        features: [
          {
            name: "drill-down",
            type: "standard",
            description: "Hierarchical data exploration",
            requiredPermissions: ["reports.consolidated"],
          },
          {
            name: "currency",
            type: "standard",
            description: "Automatic currency conversion",
            requiredPermissions: ["reports.consolidated"],
          },
          {
            name: "eliminations",
            type: "enterprise",
            description: "Intercompany elimination entries",
            requiredPermissions: ["reports.consolidated.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "franchise",
        label: "Franchise Management",
        features: [
          {
            name: "royalties",
            type: "standard",
            description: "Royalty calculation engine",
            requiredPermissions: ["franchise.manage"],
          },
          {
            name: "compliance",
            type: "advanced",
            description: "Brand standards compliance tracking",
            requiredPermissions: ["franchise.compliance"],
            premium: true,
          },
          {
            name: "portal",
            type: "enterprise",
            description: "Franchisee self-service portal",
            requiredPermissions: ["franchise.portal"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "geo_analytics",
        label: "Geographic Analytics",
        features: [
          {
            name: "heatmaps",
            type: "standard",
            description: "Sales density visualization",
            requiredPermissions: ["analytics.geo"],
          },
          {
            name: "demographics",
            type: "advanced",
            description: "Customer demographic overlays",
            requiredPermissions: ["analytics.geo.advanced"],
            premium: true,
          },
          {
            name: "site_selection",
            type: "enterprise",
            description: "New location predictive modeling",
            requiredPermissions: ["analytics.geo.site"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "central_kitchen",
        label: "Central Kitchen Management",
        premium: true,
        features: [
          {
            name: "production",
            type: "premium",
            description: "Batch production planning",
            requiredPermissions: ["kitchen.central"],
            premium: true,
          },
          {
            name: "distribution",
            type: "premium",
            description: "Multi-location distribution scheduling",
            requiredPermissions: ["kitchen.central"],
            premium: true,
          },
          {
            name: "yield",
            type: "enterprise",
            description: "Ingredient yield optimization",
            requiredPermissions: ["kitchen.central.advanced"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "customer",
    label: "Customer Hub",
    icon: "users",
    subMenu: [
      {
        id: 1,
        name: "crm",
        label: "CRM Dashboard",
        features: [
          {
            name: "360-view",
            type: "standard",
            description: "Unified customer profile",
            requiredPermissions: ["crm.view"],
          },
          {
            name: "interaction",
            type: "standard",
            description: "Customer interaction history",
            requiredPermissions: ["crm.view"],
          },
          {
            name: "preferences",
            type: "advanced",
            description: "Detailed preference tracking",
            requiredPermissions: ["crm.advanced"],
            premium: true,
          },
        ],
      },
      {
        id: 2,
        name: "loyalty",
        label: "Loyalty Programs",
        features: [
          {
            name: "tiers",
            type: "standard",
            description: "Multi-tier reward levels",
            requiredPermissions: ["loyalty.manage"],
          },
          {
            name: "burn",
            type: "standard",
            description: "Point redemption processing",
            requiredPermissions: ["loyalty.manage"],
          },
          {
            name: "partnerships",
            type: "enterprise",
            description: "Cross-brand loyalty partnerships",
            requiredPermissions: ["loyalty.partners"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "feedback",
        label: "Feedback System",
        features: [
          {
            name: "sentiment",
            type: "standard",
            description: "Sentiment analysis",
            requiredPermissions: ["feedback.view"],
          },
          {
            name: "nps",
            type: "standard",
            description: "Net Promoter Score tracking",
            requiredPermissions: ["feedback.view"],
          },
          {
            name: "resolution",
            type: "advanced",
            description: "Complaint resolution workflow",
            requiredPermissions: ["feedback.manage"],
            premium: true,
          },
        ],
      },
      {
        id: 4,
        name: "marketing",
        label: "Marketing Automation",
        features: [
          {
            name: "campaigns",
            type: "standard",
            description: "Multi-channel campaign management",
            requiredPermissions: ["marketing.manage"],
          },
          {
            name: "segmentation",
            type: "standard",
            description: "Customer segmentation engine",
            requiredPermissions: ["marketing.manage"],
          },
          {
            name: "attribution",
            type: "enterprise",
            description: "Campaign ROI attribution",
            requiredPermissions: ["marketing.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "gift_cards",
        label: "Gift Card Management",
        features: [
          {
            name: "issuance",
            type: "standard",
            description: "Physical/digital card issuance",
            requiredPermissions: ["giftcards.manage"],
          },
          {
            name: "balances",
            type: "standard",
            description: "Real-time balance checking",
            requiredPermissions: ["giftcards.view"],
          },
          {
            name: "fraud",
            type: "enterprise",
            description: "Fraud detection patterns",
            requiredPermissions: ["giftcards.security"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "memberships",
        label: "Membership Programs",
        features: [
          {
            name: "renewals",
            type: "standard",
            description: "Automatic membership renewals",
            requiredPermissions: ["memberships.manage"],
          },
          {
            name: "benefits",
            type: "standard",
            description: "Tiered benefit structures",
            requiredPermissions: ["memberships.manage"],
          },
          {
            name: "retention",
            type: "enterprise",
            description: "Churn prevention analytics",
            requiredPermissions: ["memberships.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 7,
        name: "customer_portal",
        label: "Customer Self-Service",
        premium: true,
        features: [
          {
            name: "orders",
            type: "premium",
            description: "Order history and tracking",
            requiredPermissions: ["portal.manage"],
            premium: true,
          },
          {
            name: "preferences",
            type: "premium",
            description: "Account preference management",
            requiredPermissions: ["portal.manage"],
            premium: true,
          },
          {
            name: "messaging",
            type: "enterprise",
            description: "Integrated messaging center",
            requiredPermissions: ["portal.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 8,
        name: "voice_of_customer",
        label: "Voice of Customer",
        enterprise: true,
        features: [
          {
            name: "text_analytics",
            type: "enterprise",
            description: "Unstructured feedback analysis",
            requiredPermissions: ["voc.analyze"],
            enterprise: true,
          },
          {
            name: "journey",
            type: "enterprise",
            description: "Customer journey mapping",
            requiredPermissions: ["voc.analyze"],
            enterprise: true,
          },
          {
            name: "clustering",
            type: "enterprise",
            description: "Automated feedback categorization",
            requiredPermissions: ["voc.advanced"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    name: "hr",
    label: "HR & Payroll",
    icon: "user-tie",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "employee",
        label: "Employee Management",
        features: [
          {
            name: "onboarding",
            type: "standard",
            description: "New hire onboarding workflow",
            requiredPermissions: ["employees.manage"],
          },
          {
            name: "documents",
            type: "standard",
            description: "Digital document storage",
            requiredPermissions: ["employees.manage"],
          },
          {
            name: "succession",
            type: "enterprise",
            description: "Succession planning tools",
            requiredPermissions: ["employees.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "scheduling",
        label: "Scheduling & Time Tracking",
        features: [
          {
            name: "auto-scheduling",
            type: "standard",
            description: "AI-assisted shift scheduling",
            requiredPermissions: ["schedule.manage"],
          },
          {
            name: "compliance",
            type: "standard",
            description: "Labor law compliance checks",
            requiredPermissions: ["schedule.manage"],
          },
          {
            name: "optimization",
            type: "enterprise",
            description: "Labor cost optimization",
            requiredPermissions: ["schedule.optimize"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "payroll",
        label: "Payroll Processing",
        features: [
          {
            name: "tax-filing",
            type: "standard",
            description: "Automated tax calculations and filings",
            requiredPermissions: ["payroll.process"],
          },
          {
            name: "garnishments",
            type: "advanced",
            description: "Wage garnishment processing",
            requiredPermissions: ["payroll.advanced"],
            premium: true,
          },
          {
            name: "international",
            type: "enterprise",
            description: "Multi-country payroll support",
            requiredPermissions: ["payroll.international"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "performance",
        label: "Performance Tracking",
        features: [
          {
            name: "kpi",
            type: "standard",
            description: "Key performance indicators",
            requiredPermissions: ["performance.manage"],
          },
          {
            name: "reviews",
            type: "standard",
            description: "Performance review cycles",
            requiredPermissions: ["performance.manage"],
          },
          {
            name: "calibration",
            type: "enterprise",
            description: "Cross-team performance calibration",
            requiredPermissions: ["performance.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "training",
        label: "Training Modules",
        features: [
          {
            name: "certifications",
            type: "standard",
            description: "Skills certification tracking",
            requiredPermissions: ["training.manage"],
          },
          {
            name: "compliance",
            type: "standard",
            description: "Required training management",
            requiredPermissions: ["training.manage"],
          },
          {
            name: "lms",
            type: "enterprise",
            description: "Learning management system integration",
            requiredPermissions: ["training.lms"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "labor_analytics",
        label: "Labor Cost Optimization",
        premium: true,
        features: [
          {
            name: "forecasting",
            type: "premium",
            description: "Labor demand forecasting",
            requiredPermissions: ["labor.analytics"],
            premium: true,
          },
          {
            name: "benchmarking",
            type: "premium",
            description: "Industry benchmarking",
            requiredPermissions: ["labor.analytics"],
            premium: true,
          },
          {
            name: "prescriptive",
            type: "enterprise",
            description: "AI-powered recommendations",
            requiredPermissions: ["labor.analytics.ai"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    name: "ecommerce",
    label: "E-Commerce",
    icon: "shopping-cart",
    subMenu: [
      {
        id: 1,
        name: "online_orders",
        label: "Online Order Management",
        features: [
          {
            name: "aggregation",
            type: "standard",
            description: "Unified order management across channels",
            requiredPermissions: ["ecommerce.orders"],
          },
          {
            name: "fraud",
            type: "advanced",
            description: "Fraud detection scoring",
            requiredPermissions: ["ecommerce.orders.fraud"],
            premium: true,
          },
          {
            name: "rules",
            type: "enterprise",
            description: "Custom order processing rules",
            requiredPermissions: ["ecommerce.orders.rules"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "menu_sync",
        label: "Menu Synchronization",
        features: [
          {
            name: "real-time",
            type: "standard",
            description: "Instant menu updates across all channels",
            requiredPermissions: ["ecommerce.menu"],
          },
          {
            name: "versioning",
            type: "advanced",
            description: "Menu change history and rollback",
            requiredPermissions: ["ecommerce.menu.advanced"],
            premium: true,
          },
          {
            name: "geofencing",
            type: "enterprise",
            description: "Location-based menu variations",
            requiredPermissions: ["ecommerce.menu.geo"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "delivery",
        label: "Delivery Integration",
        features: [
          {
            name: "dispatch",
            type: "standard",
            description: "Driver dispatch and tracking",
            requiredPermissions: ["delivery.manage"],
          },
          {
            name: "zones",
            type: "standard",
            description: "Delivery zone management",
            requiredPermissions: ["delivery.manage"],
          },
          {
            name: "dynamic",
            type: "enterprise",
            description: "Dynamic pricing by distance/time",
            requiredPermissions: ["delivery.pricing"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "marketplace",
        label: "Marketplace Connectors",
        features: [
          {
            name: "multi-channel",
            type: "standard",
            description: "Sync with major marketplaces",
            requiredPermissions: ["ecommerce.integrations"],
          },
          {
            name: "inventory",
            type: "advanced",
            description: "Real-time inventory sync",
            requiredPermissions: ["ecommerce.integrations.advanced"],
            premium: true,
          },
          {
            name: "fulfillment",
            type: "enterprise",
            description: "Automated fulfillment routing",
            requiredPermissions: ["ecommerce.integrations.fulfillment"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "click_collect",
        label: "Click & Collect",
        premium: true,
        features: [
          {
            name: "scheduling",
            type: "premium",
            description: "Pickup time slot management",
            requiredPermissions: ["ecommerce.pickup"],
            premium: true,
          },
          {
            name: "notifications",
            type: "premium",
            description: "Automated customer alerts",
            requiredPermissions: ["ecommerce.pickup"],
            premium: true,
          },
          {
            name: "geofencing",
            type: "enterprise",
            description: "Proximity-based check-in",
            requiredPermissions: ["ecommerce.pickup.geo"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "dark_kitchen",
        label: "Dark Kitchen Mode",
        enterprise: true,
        features: [
          {
            name: "virtual",
            type: "enterprise",
            description: "Virtual brand management",
            requiredPermissions: ["ecommerce.dark"],
            enterprise: true,
          },
          {
            name: "optimization",
            type: "enterprise",
            description: "Delivery-only operation optimization",
            requiredPermissions: ["ecommerce.dark"],
            enterprise: true,
          },
          {
            name: "analytics",
            type: "enterprise",
            description: "Delivery performance analytics",
            requiredPermissions: ["ecommerce.dark.analytics"],
            enterprise: true,
          },
        ],
      },
      {
        id: 7,
        name: "qr_shopping",
        label: "Mobile QR Shopping",
        features: [
          {
            name: "inventory_lookup",
            type: "standard",
            description: "Real-time inventory availability check",
            requiredPermissions: ["ecommerce.qr"],
          },
          {
            name: "cart_sync",
            type: "advanced",
            description: "Synchronized cart across devices",
            requiredPermissions: ["ecommerce.qr.advanced"],
            premium: true,
          },
          {
            name: "pos_payment_link",
            type: "enterprise",
            description: "Seamless POS payment integration",
            requiredPermissions: ["ecommerce.qr.pos"],
            enterprise: true,
          },
        ],
        integration: {
          pos: true,
          inventory: true,
          payment: true,
        },
      },
    ],
  },
  {
    id: 9,
    name: "system",
    label: "System Administration",
    icon: "cogs",
    adminOnly: true,
    subMenu: [
      {
        id: 1,
        name: "users",
        label: "User & Role Management",
        features: [
          {
            name: "mfa",
            type: "standard",
            description: "Multi-factor authentication enforcement",
            requiredPermissions: ["admin.users"],
          },
          {
            name: "provisioning",
            type: "advanced",
            description: "Bulk user import/export",
            requiredPermissions: ["admin.users.bulk"],
            premium: true,
          },
          {
            name: "sso",
            type: "enterprise",
            description: "Single sign-on integration",
            requiredPermissions: ["admin.users.sso"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "permissions",
        label: "Permission Matrix",
        features: [
          {
            name: "granular",
            type: "standard",
            description: "Role-based access control",
            requiredPermissions: ["admin.permissions"],
          },
          {
            name: "templates",
            type: "standard",
            description: "Predefined permission sets",
            requiredPermissions: ["admin.permissions"],
          },
          {
            name: "audit",
            type: "enterprise",
            description: "Permission change tracking",
            requiredPermissions: ["admin.permissions.audit"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "integrations",
        label: "API & Integrations",
        features: [
          {
            name: "webhooks",
            type: "standard",
            description: "Outbound event notifications",
            requiredPermissions: ["admin.integrations"],
          },
          {
            name: "marketplace",
            type: "advanced",
            description: "App marketplace connectivity",
            requiredPermissions: ["admin.integrations.marketplace"],
            premium: true,
          },
          {
            name: "monitoring",
            type: "enterprise",
            description: "Integration health monitoring",
            requiredPermissions: ["admin.integrations.monitor"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "backup",
        label: "Backup & Restore",
        features: [
          {
            name: "cloud",
            type: "standard",
            description: "Automated cloud backups",
            requiredPermissions: ["admin.backup"],
          },
          {
            name: "point-in-time",
            type: "advanced",
            description: "Point-in-time recovery",
            requiredPermissions: ["admin.backup.advanced"],
            premium: true,
          },
          {
            name: "disaster",
            type: "enterprise",
            description: "Disaster recovery planning",
            requiredPermissions: ["admin.backup.disaster"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "hardware",
        label: "Hardware Configuration",
        features: [
          {
            name: "profiles",
            type: "standard",
            description: "Device-specific configuration sets",
            requiredPermissions: ["admin.hardware"],
          },
          {
            name: "remote",
            type: "advanced",
            description: "Remote device management",
            requiredPermissions: ["admin.hardware.remote"],
            premium: true,
          },
          {
            name: "kiosk",
            type: "enterprise",
            description: "Kiosk mode lockdown",
            requiredPermissions: ["admin.hardware.kiosk"],
            enterprise: true,
          },
        ],
      },
      {
        id: 6,
        name: "license",
        label: "License Management",
        features: [
          {
            name: "usage",
            type: "standard",
            description: "License utilization tracking",
            requiredPermissions: ["admin.license"],
          },
          {
            name: "compliance",
            type: "advanced",
            description: "License compliance reporting",
            requiredPermissions: ["admin.license.compliance"],
            premium: true,
          },
          {
            name: "pooling",
            type: "enterprise",
            description: "Floating license pools",
            requiredPermissions: ["admin.license.pooling"],
            enterprise: true,
          },
        ],
      },
      {
        id: 7,
        name: "support",
        label: "Issue Tracker / Support Requests",
        features: [
          {
            name: "sla",
            type: "standard",
            description: "Service level agreement tracking",
            requiredPermissions: ["admin.support"],
          },
          {
            name: "escalation",
            type: "advanced",
            description: "Automated ticket escalation",
            requiredPermissions: ["admin.support.escalate"],
            premium: true,
          },
          {
            name: "knowledge",
            type: "enterprise",
            description: "Integrated knowledge base",
            requiredPermissions: ["admin.support.knowledge"],
            enterprise: true,
          },
        ],
      },
      {
        id: 8,
        name: "release_notes",
        label: "Release Notes & Updates",
        features: [
          {
            name: "changelog",
            type: "standard",
            description: "Detailed version history",
            requiredPermissions: ["admin.updates"],
          },
          {
            name: "scheduling",
            type: "advanced",
            description: "Update deployment scheduling",
            requiredPermissions: ["admin.updates.schedule"],
            premium: true,
          },
          {
            name: "rollback",
            type: "enterprise",
            description: "Version rollback capability",
            requiredPermissions: ["admin.updates.rollback"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 10,
    name: "audit",
    label: "Audit & Compliance",
    icon: "shield-alt",
    subMenu: [
      {
        id: 1,
        name: "activity_logs",
        label: "Activity Audit Trail",
        features: [
          {
            name: "reconstruction",
            type: "standard",
            description: "Historical session reconstruction",
            requiredPermissions: ["audit.view"],
          },
          {
            name: "filtering",
            type: "standard",
            description: "Advanced search and filtering",
            requiredPermissions: ["audit.view"],
          },
          {
            name: "anomaly",
            type: "enterprise",
            description: "Anomaly detection alerts",
            requiredPermissions: ["audit.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "financial_audit",
        label: "Financial Auditing",
        features: [
          {
            name: "snapshots",
            type: "standard",
            description: "Period-end financial snapshots",
            requiredPermissions: ["audit.financial"],
          },
          {
            name: "approval",
            type: "standard",
            description: "Change approval workflows",
            requiredPermissions: ["audit.financial"],
          },
          {
            name: "segregation",
            type: "enterprise",
            description: "Duty segregation enforcement",
            requiredPermissions: ["audit.financial.advanced"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "pci_compliance",
        label: "PCI Compliance",
        features: [
          {
            name: "scans",
            type: "standard",
            description: "Vulnerability scanning",
            requiredPermissions: ["compliance.pci"],
          },
          {
            name: "reporting",
            type: "advanced",
            description: "Compliance documentation generation",
            requiredPermissions: ["compliance.pci.report"],
            premium: true,
          },
          {
            name: "tokenization",
            type: "enterprise",
            description: "Payment data tokenization",
            requiredPermissions: ["compliance.pci.token"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "data_export",
        label: "Regulatory Exports",
        features: [
          {
            name: "templates",
            type: "standard",
            description: "Predefined regulatory report templates",
            requiredPermissions: ["compliance.export"],
          },
          {
            name: "scheduling",
            type: "standard",
            description: "Automated report generation",
            requiredPermissions: ["compliance.export"],
          },
          {
            name: "validation",
            type: "enterprise",
            description: "Data validation rules engine",
            requiredPermissions: ["compliance.export.validate"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "sarbanes_oxley",
        label: "SOX Controls",
        enterprise: true,
        features: [
          {
            name: "documentation",
            type: "enterprise",
            description: "Control documentation management",
            requiredPermissions: ["compliance.sox"],
            enterprise: true,
          },
          {
            name: "testing",
            type: "enterprise",
            description: "Control testing workflows",
            requiredPermissions: ["compliance.sox"],
            enterprise: true,
          },
          {
            name: "remediation",
            type: "enterprise",
            description: "Deficiency tracking and remediation",
            requiredPermissions: ["compliance.sox"],
            enterprise: true,
          },
        ],
      },
    ],
  },
  {
    id: 11,
    name: "advanced",
    label: "Advanced Features",
    icon: "magic",
    enterprise: true,
    subMenu: [
      {
        id: 1,
        name: "ai",
        label: "AI Recommendations",
        premium: true,
        features: [
          {
            name: "upsell",
            type: "premium",
            description: "Real-time product recommendations",
            requiredPermissions: ["ai.recommend"],
            premium: true,
          },
          {
            name: "pricing",
            type: "enterprise",
            description: "Dynamic pricing optimization",
            requiredPermissions: ["ai.pricing"],
            enterprise: true,
          },
          {
            name: "allocation",
            type: "enterprise",
            description: "Smart inventory allocation",
            requiredPermissions: ["ai.inventory"],
            enterprise: true,
          },
        ],
      },
      {
        id: 2,
        name: "recipe",
        label: "Recipe & Menu Engineering",
        features: [
          {
            name: "costing",
            type: "standard",
            description: "Ingredient-level cost analysis",
            requiredPermissions: ["menu.engineer"],
          },
          {
            name: "yield",
            type: "advanced",
            description: "Production yield tracking",
            requiredPermissions: ["menu.engineer.advanced"],
            premium: true,
          },
          {
            name: "optimization",
            type: "enterprise",
            description: "Menu profitability optimization",
            requiredPermissions: ["menu.engineer.optimize"],
            enterprise: true,
          },
        ],
      },
      {
        id: 3,
        name: "waste",
        label: "Waste Tracking",
        features: [
          {
            name: "root-cause",
            type: "standard",
            description: "Waste reason coding",
            requiredPermissions: ["inventory.waste"],
          },
          {
            name: "trends",
            type: "advanced",
            description: "Waste pattern analysis",
            requiredPermissions: ["inventory.waste.analyze"],
            premium: true,
          },
          {
            name: "ai",
            type: "enterprise",
            description: "Predictive waste reduction",
            requiredPermissions: ["inventory.waste.ai"],
            enterprise: true,
          },
        ],
      },
      {
        id: 4,
        name: "kds",
        label: "Kitchen Display System",
        features: [
          {
            name: "ai-routing",
            type: "enterprise",
            description: "Smart order routing to stations",
            requiredPermissions: ["kitchen.kds"],
            enterprise: true,
          },
          {
            name: "timing",
            type: "standard",
            description: "Order timing analytics",
            requiredPermissions: ["kitchen.kds"],
          },
          {
            name: "integration",
            type: "enterprise",
            description: "Equipment integration",
            requiredPermissions: ["kitchen.kds.integrate"],
            enterprise: true,
          },
        ],
      },
      {
        id: 5,
        name: "reservations",
        label: "Reservation System",
        features: [
          {
            name: "yield",
            type: "enterprise",
            description: "Revenue yield management",
            requiredPermissions: ["reservations.manage"],
            enterprise: true,
          },
          {
            name: "prepaid",
            type: "advanced",
            description: "Prepaid reservation deposits",
            requiredPermissions: ["reservations.deposits"],
            premium: true,
          },
          {
            name: "preferences",
            type: "standard",
            description: "Customer preference tracking",
            requiredPermissions: ["reservations.manage"],
          },
        ],
      },
      {
        id: 6,
        name: "product_lifecycle",
        label: "Product Lifecycle Mgmt",
        features: [
          {
            name: "phase",
            type: "standard",
            description: "Product lifecycle stage tracking",
            requiredPermissions: ["products.lifecycle"],
          },
          {
            name: "performance",
            type: "advanced",
            description: "Performance analytics by phase",
            requiredPermissions: ["products.lifecycle.analyze"],
            premium: true,
          },
          {
            name: "transition",
            type: "enterprise",
            description: "Automated phase transitions",
            requiredPermissions: ["products.lifecycle.auto"],
            enterprise: true,
          },
        ],
      },
      {
        id: 7,
        name: "iot",
        label: "IoT Device Integration",
        premium: true,
        features: [
          {
            name: "monitoring",
            type: "premium",
            description: "Equipment monitoring",
            requiredPermissions: ["iot.monitor"],
            premium: true,
          },
          {
            name: "alerts",
            type: "premium",
            description: "Predictive maintenance alerts",
            requiredPermissions: ["iot.alerts"],
            premium: true,
          },
          {
            name: "automation",
            type: "enterprise",
            description: "Workflow automation triggers",
            requiredPermissions: ["iot.automate"],
            enterprise: true,
          },
        ],
      },
      {
        id: 8,
        name: "blockchain",
        label: "Blockchain Traceability",
        enterprise: true,
        features: [
          {
            name: "provenance",
            type: "enterprise",
            description: "Ingredient provenance tracking",
            requiredPermissions: ["blockchain.track"],
            enterprise: true,
          },
          {
            name: "smart",
            type: "enterprise",
            description: "Smart contract integration",
            requiredPermissions: ["blockchain.contracts"],
            enterprise: true,
          },
          {
            name: "compliance",
            type: "enterprise",
            description: "Automated compliance reporting",
            requiredPermissions: ["blockchain.compliance"],
            enterprise: true,
          },
        ],
      },
    ],
  },
];
