name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          mkdir -p dist
          npm run build || (echo "Build failed" && exit 1)

      - name: Verify build output
        run: |
          echo "Build contents:"
          ls -la dist/
          echo "Total files:"
          find dist/ -type f | wc -l

      - name: Deploy to Namecheap
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.NAMECHEAP_HOST }}
          username: ${{ secrets.NAMECHEAP_USERNAME }}
          password: ${{ secrets.NAMECHEAP_PASSWORD }}
          local-dir: dist/
          server-dir: pos.unidezk.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.md
            **/*.json
            **/*.config.*
